universe           = vanilla
executable         = runSkim.sh
getenv = True
arguments          = $(inputPath) $(num) 
output             = logs/$(Cluster)_$(Process).out
error              = logs/$(Cluster)_$(Process).err
log                = logs/$(Cluster)_$(Process).log
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = FlexibleFlattener.cpp, combined_file_list.txt

queue inputPath num from combined_file_list.txt


