universe           = vanilla
executable         = runProcess_MC.sh
getenv = True
arguments          = $(start) $(end) $(job_idx) $(type) $(path)
output             = logs/$(Cluster)_$(Process).out
error              = logs/$(Cluster)_$(Process).err
log                = logs/$(Cluster)_$(Process).log
request_memory = 4 GB
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
queue start end job_idx type path from files.txt


